name: seal
channels:
  - conda-forge
  - bioconda
  - fescudie
  - defaults
dependencies:
  - python<3.9
  - tzlocal=2.1
  - flask=1.1.2
  - flask-sqlalchemy=2.5.1
  - flask-wtf=0.15.1
  - flask-bcrypt=0.7.1
  - flask-admin=1.5.8
  - flask-login=0.5.0
  - flask-apscheduler=1.12.2
  - flask-testing=0.8.1
  - flask-restful=0.3.9
  - email_validator=1.1.3
  - pillow=8.3.1
  - pytest=6.2.4
  - pandas>=1.1.5
  - postgresql=13.3
  - psycopg2=2.8.6
  - anacore=2.9
  - flask-migrate=3.1.0
  - ensembl-vep=104.3
