name: seal
channels:
  - conda-forge
  - defaults
dependencies:
  - python<3.9
  - flask=1.1.2
  - flask-sqlalchemy=2.5.1
  - flask-wtf=0.15.1
  - flask-bcrypt=0.7.1
  - flask-login=0.5.0
  - email_validator=1.1.3
  - pillow=8.3.1
  - pytest=6.2.4
  - flask-testing=0.8.1
  - postgresql=13.3
  - psycopg2=2.8.6
  - anacore=2.9
  - flask-apscheduler=1.12.2
